[profile.default]
fs_permissions = [{ access = "read-write", path = "./"}]
private_key = "${SEPOLIA_PRIVATE_KEY}" # 私钥的环境变量
gas_price = 20000000000   # 20 gwei，基本费用
gasTipCap = 20000000001  # 20 gwei，小费

[rpc_endpoints]
# The RPC URLs are modified versions of the default for testing initialization.
# mainnet = "https://eth-mainnet.alchemyapi.io/v2/WV407BEiBmjNJfKo9Uo_55u0z0ITyCOX" # Different API key.
# optimism_sepolia = "https://sepolia.optimism.io/" # Adds a trailing slash.
# arbitrum_one_sepolia = "https://sepolia-rollup.arbitrum.io/rpc/" # Adds a trailing slash.
# 这是一个未定义的环境变量占位符，用于在配置中指定RPC URL
# needs_undefined_env_var = "${UNDEFINED_RPC_URL_PLACEHOLDER}"
sepolia = "${SEPOLIA_RPC_URL}"
neox = "https://neoxt4seed1.ngd.network"


[fmt]
# These are all the `forge fmt` defaults.
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = 'long'
multiline_func_header = 'attributes_first'
quote_style = 'double'
number_underscore = 'preserve'
single_line_statement_blocks = 'preserve'
ignore = ["src/console.sol", "src/console2.sol"]